services:
  mysql:
    image: mysql:latest
    container_name: mysql-quiz-container
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: quiz_db
       MYSQL_USER: user
       MYSQL_PASSWORD: pass
    ports:
        - '3307:3307'
    volumes:
        - ./mysql_data:/var/lib/mysql
    networks:
        - spring-mysql

  springboot:
    build: .
    container_name: QuizApp
    environment:
      SERVER_PORT: 8090
      MYSQL_HOST: mysql # Replace with the host of your existing MySQL container
      MYSQL_PORT: 3307 # Replace with the port of your existing MySQL container
      MYSQL_DB: quiz_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
        - "8090:8090"
    networks:
        - spring-mysql

volumes:
    mysql_data:

networks:
    spring-mysql:
        driver : bridge